# Generated by Django 4.2.25 on 2025-10-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='language_name',
        ),
        migrations.RenameField(
            model_name='moviecast',
            old_name='movie',
            new_name='movie_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='person_name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default=None),
        ),
    ]
