# Generated by Django 4.2.25 on 2025-11-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_review_user_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user_name', 'movie_name'), name='unique_review'),
        ),
    ]
