# Generated by Django 4.2.25 on 2025-10-27 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_duration_alter_movie_poster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language_name',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='movielanguage',
            old_name='movie',
            new_name='movie_name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='movie_name',
        ),
        migrations.AlterUniqueTogether(
            name='movielanguage',
            unique_together={('movie_name', 'language')},
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100)),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('person', models.ForeignKey(limit_choices_to={'role_type': 'actor'}, on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
            ],
            options={
                'unique_together': {('movie_name', 'person')},
            },
        ),
    ]
