# Generated by Django 4.2.25 on 2025-10-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_language_name_language_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='language',
        ),
    ]
