# Generated by Django 4.2.25 on 2025-10-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_language_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language',
            field=models.CharField(default='mixlang', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
