# Generated by Django 4.2.25 on 2025-11-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_person_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
