# Generated by Django 4.2.25 on 2025-11-12 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_person_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecast',
            name='director',
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(limit_choices_to={'role_type': 'director'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_movies', to='movies.person'),
        ),
    ]
