# Generated by Django 4.2.25 on 2025-11-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_remove_moviecast_director_alter_movie_director'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('rating__range', (1, 10))), name='rating_in_range'),
        ),
    ]
